### PR TITLE
Sean week5

### PR DESCRIPTION
**Pull request by SPD3**
My Week 5 Notebook entry

### CODE REVIEW

**Comment by rishyak** [comment]
If you are working on a fork, you want to keep main unchanged from upstream (the source you forked from a.k.a. this repo) so you can easily merge changes from upstream (this is called fast-forwarding). That would prevent merge commits, like this one: [424335d](https://github.com/NYU-Processor-Design/nyu-processor-design.github.io/pull/72/commits/424335d7d5303d0418a630f216f0d6eb54bc4d85).

To make any changes, make a branch:
```console
git switch -c week123
```
This creates (`-c` flag) and switches to the branch. You can do this in two steps by:
```console
git branch week123
git switch week123
```

`week123` is the branch name, you could choose anything you like. 

Then make your changes, commit, push. PR from your fork. Once it's merged, you can delete your branch:
```console
git switch main
git branch -D docs
```
You need to switch first because you can't delete a branch you have checked out (git for "a branch you are currently hacking on"). 

`-d` is delete and `-D` is force delete. The reason you want to force delete is because git will yell at you if you try to delete a branch which hasn't been merged anywhere. 

---

All your PR's should ideally come from separate branches. 

---

If you have any questions on how to clean this up or how to work with branches, feel free to ask here or DM me.

**Comment by rishyak** [comment]
To clean your main branch, follow the following steps:

1. Create a branch from your current head so you don't lose changes
  ```console
  git branch oldmain
  ```

1. Clean up main
  ```console
  git fetch upstream
  git reset --hard upstream/main
  ```

1. Force-push changes to origin (your remote)
  ```console
  git push -f
  ```

1. Create a branch for your design notebook entry for this week
  ```console
  git switch -c sean
  ```

1. Cherry-pick your design-notebook entry to your branch
  ```console
  git cherry-pick "44026dc^..1a5494c"
  ```
  **Note:** We don't expect you to know cherry-picking or even regularly use it. If you're interested in why this works, look it up in the Pro Git Book.

  We also don't want to rebase from `oldmain` because that will bring the merge commit along, which is what we're trying to avoid in the first place.


Optionally: Squash the previous two commits into one glorious single-commit if you know how interactive rebasing works
  ```console
  git rebase -i HEAD~2
  ```
  If not, that's fine, we'll squash and merge your commits. 

7, Create a beautiful PR.

**Comment by SPD3** [comment]
Hey Rishyak,

Could you elaborate a little more on why merging main into the branch I am PRing is not desirable? You said that I "want to keep main unchanged from upstream" but I don't think I understand what this means. Also what needs to be cleaned up with my main branch right now to do this fetch and reset that you described in your second post? I haven't changed my main at all since running sync-fork today so I don't really know what resetting will do to it (maybe this is just me not understanding forks, as they are not how I am used to using git)? It looks like what you described would change my PR by just getting rid of that one merge but I don't see where my main branch would change.

Thanks
-Sean Doyle

**Comment by rishyak** [comment]
Answering your questions in the next comment but it seems like the merge commits exist because you branched from the SeanWeek4 branch. Ideally, you want to branch from main so it is easier to merge your PR's.

**Comment by rishyak** [comment]
> Could you elaborate a little more on why merging main into the branch I am PRing is not desirable? You said that I "want to keep main unchanged from upstream" but I don't think I understand what this means. 

Having merge commits pollutes origin (your fork) and that makes it hard for git to easily incorporate changes from upstream (this repo). 

In an ideal world, when you sync your forks (through GitHub or locally), git will simply move the head pointer from origin's head to upstream's head. This is called [fast-forwarding](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging). 

When your main is polluted, git can't simply fast-forward. Instead, it has to "merge" the branches which causes merge commits. In the worst of cases, you might get merge conflicts and have to clean that up.

When working on forks of projects with constant changes, it is more convenient to work on branches on your fork to allow fast-forwarding.

The reset will make your fork sync with upstream. Your worktree and upstream's worktree will be one and the same. Every commit on upstream will be on your repo. This will cause you to lose all other commits that aren't on upstream. 

As the name suggests, this is a hard reset of your fork.

---

> Also what needs to be cleaned up with my main branch right now to do this fetch and reset that you described in your second post? 

Nothing needs to be changed.

---

>  I haven't changed my main at all since running sync-fork today so I don't really know what resetting will do to it (maybe this is just me not understanding forks, as they are not how I am used to using git)?

It will do nothing. I copied my comment from another PR here without looking into it too much because the patterns seemed similar. 

---

> It looks like what you described would change my PR by just getting rid of that one merge but I don't see where my main branch would change.

It won't change your main, but it will create PR's without merge commits.

**Comment by SPD3** [comment]
So are you saying that by merging my main branch into my SeanWeek5 branch it will make it more difficult for me to do a sync-fork later because I could run into merge conflicts, instead of the sync just being fast forward?

**Comment by nickelpro** [comment]
This is mostly my fault for letting these PRs linger for a week, fixing now

**Comment by rishyak** [comment]
> So are you saying that by merging my main branch into my SeanWeek5 branch it will make it more difficult for me to do a sync-fork later because I could run into merge conflicts, instead of the sync just being fast forward?

Pretty much. 

---

Also to be very clear:
- "Sync-fork" is a GitHub thing
- You can also do it locally
- There are many ways to do this but if you keep your main clean, you can just pull from upstream and push to origin (how I like to do it)
```console
git pull upstream main
git push origin main
```
- Docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Pull request merged**
