### PR TITLE
first changes

### PR DESCRIPTION
**Pull request by sharan-16**

### CODE REVIEW

**Comment by sharan-16** [comment]
first changes

**Comment by sharan-16** [comment]
first changes

**Comment by sharan-16** [comment]
.

**Comment by sharan-16** [comment]
.

**Comment by rishyak** [comment]
Hi Sharan, since this is your first page, I recommend you look at the following:
- https://nyu-processor-design.github.io/getting_started/notebooks/04_first_pr.html
- https://nyu-processor-design.github.io/getting_started/notebooks/05_collab.html

**Comment by sharan-16** [comment]
Hey Rishyak thanks I'll go through them

**Pull request closed without merging**
