### PR TITLE
feat: finished lab 2

### PR DESCRIPTION
**Pull request by aminoa**

### CODE REVIEW

**Comment by nickelpro** [comment]
Work with @rishyak or @umanachi to resolve merge conflicts

**Comment by rishyak** [comment]
If you're inclined to figure it out yourself, [here's a guide](https://nyu-processor-design.github.io/getting_started/notebooks/05_collab.html). We're happy to help too, so don't be afraid to reach out.

**Comment by aminoa** [comment]
I fixed the merge conflict issue here

**Comment by rishyak** [comment]
Although technically fixed, there is still a workflow issue here. Reach out and we'll talk about it.

**Pull request closed without merging**
