### PR TITLE
docs(dn): update rishyak notebook 2023-02-05

### PR DESCRIPTION
**Pull request by rishyak**
Finished lab 4.

### CODE REVIEW

**Comment by nickelpro** [comment]
Well you're faster than me.

If you have questions about `nyu-cmake` feel free to forward them to me, `nyu-util` is barely a thing at the moment (it generates reports for codecov) but same idea. I'm not opposed to documenting them it just wasn't a priority.

I'll merge this on Friday, feel free to push more to it

**Comment by rishyak** [comment]
Yeah I went through `nu-util` and pretty much figured what it's doing. If you look at my lab 4 repo, I'm getting it setup for coverage.

**Comment by nickelpro** [comment]
@rishyak 

Just looked at your lab 4 answers.

Templates! You can't compile a template before some code provides an instantiation, a monomorphization of it (or, well, you can't _completely_ compile it). Template libraries are always distributed as pure source code ("header-only"), so they're always interface libraries.

**Comment by rishyak** [comment]
Right, in my mind C++ is not a language that provides generic types. That's reserved for Rust, Go (even though they only recently got true generics), etc.

**Pull request merged**
